[build]
  publish = "public"
  command = "vite build && cp -r dist/public/assets public/ && cp dist/public/index.html public/index.html"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "20"